name: tp1
services:
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    image: gateway:latest
    networks:
      - testing_net
    depends_on:
      - filter_indie
    volumes:
      - ./common:/common
    environment:
      - LOGGING_LEVEL=DEBUG
      - OUTPUT_EXCHANGES=["games"]
      - INPUT_QUEUES={"result_queue":"result_queue"}
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client:latest
    networks:
      - testing_net
    depends_on:
      - gateway
    environment:
      - LOGGING_LEVEL=INFO
      - rabbitmq_RESULTS_QUEUE=result_queue
    volumes:
      - ./client:/client
      - ./client/data:/data
      - ./client/config.ini:/client/config.ini
      - ./common:/common

  # games_counter:
  #   container_name: games_counter
  #   build:
  #     context: ./games_counter
  #     dockerfile: Dockerfile
  #   image: games_counter:latest
  #   networks:
  #     - testing_net
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   environment:
  #     - rabbitmq_HOST=rabbitmq
  #     - rabbitmq_PORT=5672
  #     - rabbitmq_GAMES_QUEUE=games_queue
  #     - rabbitmq_RESULTS_QUEUE=games_counter_results_queue
  #     - rabbitmq_USER=admin
  #     - rabbitmq_PASS=admin
  #     - LOGGING_LEVEL=INFO
  #   volumes:
  #     - ./games_counter/config.ini:/games_counter/config.ini  
  #     - ./games_counter/data:/data 
  #   entrypoint: python3 main.py

  filter_indie:
    container_name: filter_indie
    build:
      context: ./filter_indie
    image: filter_indie:latest
    networks:
      - testing_net
    environment:
      - OUTPUT_EXCHANGES=["indie_games"]
      - INPUT_QUEUES={"games_queue":"games"}
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./common:/common

  filter_range:
    container_name: filter_range
    build:
      context: ./filter_range
    image: filter_range:latest
    networks:
      - testing_net
    environment:
      - OUTPUT_EXCHANGES=["indie_range_games"]
      - INPUT_QUEUES={"indie_games_queue":"indie_games"}
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./common:/common

  top10_indie_counter:
    container_name: top10_indie_counter
    build:
      context: ./top10_indie_counter
      dockerfile: Dockerfile
    image: top10_indie_counter:latest
    networks:
      - testing_net
    depends_on:
      filter_range:
        condition: service_started
    environment:
      - rabbitmq_INPUT_QUEUE=indie_games_in_range
      - rabbitmq_RESULTS_QUEUE=result_queue
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./top10_indie_counter/config.ini:/top10_indie_counter/config.ini
      - ./top10_indie_counter/data:/data
    entrypoint: python3 main.py

networks:
  testing_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.125.0/24
