# docker-compose-system.yaml
name: tp1

services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: gateway:latest
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - rabbitmq_HOST=rabbitmq
      - rabbitmq_PORT=5672
      - rabbitmq_GAMES_QUEUE=games_queue
      - rabbitmq_REVIEWS_QUEUE=reviews_queue
      - rabbitmq_USER=admin
      - rabbitmq_PASS=admin
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./gateway:/gateway
      - ./gateway/config.ini:/gateway/config.ini  
      - ./common:/common

  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: client:latest
    networks:
      - testing_net
    depends_on:
      - gateway
    environment:
      - LOGGING_LEVEL=INFO
    volumes:
      - ./client:/client
      - ./client/data:/data  
      - ./client/config.ini:/client/config.ini 
      - ./common:/common 

  games_counter:
    container_name: games_counter
    build:
      context: ./games_counter
      dockerfile: Dockerfile
    image: games_counter:latest
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - rabbitmq_HOST=rabbitmq
      - rabbitmq_PORT=5672
      - rabbitmq_GAMES_QUEUE=games_queue
      - rabbitmq_USER=admin
      - rabbitmq_PASS=admin
      - LOGGING_LEVEL=INFO
    volumes:
      - ./games_counter/config.ini:/games_counter/config.ini  
      - ./games_counter/data:/data 
    entrypoint: python3 main.py

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24