# Batches
MAX_BATCH_SIZE = 10

# Queues
MAX_QUEUE_SIZE = 100000

# Constantes numéricas para games.csv
GAMES_APP_ID_POS = 0
GAMES_NAME_POS = 1
GAMES_RELEASE_DATE_POS = 2
GAMES_ESTIMATED_OWNERS_POS = 3
GAMES_PEAK_CCU_POS = 4
GAMES_REQUIRED_AGE_POS = 5
GAMES_PRICE_POS = 6
GAMES_DISCOUNT_DLC_COUNT_POS = 7
GAMES_ABOUT_THE_GAME_POS = 8
GAMES_SUPPORTED_LANGUAGES_POS = 9
GAMES_FULL_AUDIO_LANGUAGES_POS = 10
GAMES_REVIEWS_POS = 11
GAMES_HEADER_IMAGE_POS = 12
GAMES_WEBSITE_POS = 13
GAMES_SUPPORT_URL_POS = 14
GAMES_SUPPORT_EMAIL_POS = 15
GAMES_WINDOWS_POS = 16
GAMES_MAC_POS = 17
GAMES_LINUX_POS = 18
GAMES_METACRITIC_SCORE_POS = 19
GAMES_METACRITIC_URL_POS = 20
GAMES_USER_SCORE_POS = 21
GAMES_POSITIVE_POS = 22
GAMES_NEGATIVE_POS = 23
GAMES_SCORE_RANK_POS = 24
GAMES_ACHIEVEMENTS_POS = 25
GAMES_RECOMMENDATIONS_POS = 26
GAMES_NOTES_POS = 27
GAMES_AVERAGE_PLAYTIME_FOREVER_POS = 28
GAMES_AVERAGE_PLAYTIME_TWO_WEEKS_POS = 29
GAMES_MEDIAN_PLAYTIME_FOREVER_POS = 30
GAMES_MEDIAN_PLAYTIME_TWO_WEEKS_POS = 31
GAMES_DEVELOPERS_POS = 32
GAMES_PUBLISHERS_POS = 33
GAMES_CATEGORIES_POS = 34
GAMES_GENRES_POS = 35
GAMES_TAGS_POS = 36
GAMES_SCREENSHOTS_POS = 37
GAMES_MOVIES_POS = 38

# Constantes numéricas para reviews.csv
REVIEWS_APP_ID_POS = 0
REVIEWS_APP_NAME_POS = 1
REVIEWS_TEXT_POS = 2
REVIEWS_SCORE_POS = 3
REVIEWS_VOTES_POS = 4
